### PR TITLE
Update commander to version 2.14.1

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
Not sure why tests are failing on node 0.8 but it's probably time to drop it anyway. I'll make a PR.

**Comment by realityking** [comment]
See #11 for the dropping of Node < 4.

**Comment by honzajavorek** [comment]
Sorry for skipping this for a while. Can we upgrade `commander` to the latest version instead?

**Comment by realityking** [comment]
@honzajavorek done. But #11 should be merged first

**Pull request merged**
